import {isPlatformBrowser} from '@angular/common';
import {ChangeDetectionStrategy, Component, Inject, OnInit, PLATFORM_ID, signal} from '@angular/core';
import {DomSanitizer, SafeHtml} from '@angular/platform-browser';
import {firstValueFrom} from 'rxjs';

import {CatalogAuthService} from '../../../core/catalog-auth.service';
import {CatalogMemberApiService} from '../../../core/catalog-member-api.service';
import {CatalogMemberCard} from '../../../core/catalog.models';

@Component({
  selector: 'app-account-card',
  standalone: false,
  templateUrl: './account-card.component.html',
  styleUrls: ['./account-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class AccountCardComponent implements OnInit {
  readonly card = signal<CatalogMemberCard | null>(null);
  readonly qrSvg = signal<SafeHtml | null>(null);
  readonly loading = signal(false);
  readonly rotating = signal(false);
  readonly confirmationPending = signal(false);
  readonly errorMessage = signal<string | null>(null);
  readonly isBrowser: boolean;

  constructor(
    private readonly auth: CatalogAuthService,
    private readonly api: CatalogMemberApiService,
    private readonly sanitizer: DomSanitizer,
    @Inject(PLATFORM_ID) platformId: object,
  ) {
    this.isBrowser = isPlatformBrowser(platformId);
  }

  ngOnInit(): void {
    if (this.isBrowser) {
      void this.loadCard();
    }
  }

  async loadCard(): Promise<void> {
    if (!this.isBrowser || this.loading()) {
      return;
    }

    this.loading.set(true);
    this.errorMessage.set(null);
    try {
      const token = await this.auth.getApiAccessToken();
      const card = await firstValueFrom(this.api.getCard(token));
      await this.setCard(card);
    } catch {
      this.card.set(null);
      this.qrSvg.set(null);
      this.errorMessage.set('Votre carte n’a pas pu être chargée. Réessayez.');
    } finally {
      this.loading.set(false);
    }
  }

  beginRotation(): void {
    this.confirmationPending.set(true);
  }

  cancelRotation(): void {
    this.confirmationPending.set(false);
  }

  async confirmRotation(): Promise<void> {
    if (this.rotating()) {
      return;
    }

    this.rotating.set(true);
    this.errorMessage.set(null);
    try {
      const token = await this.auth.getApiAccessToken();
      const card = await firstValueFrom(this.api.rotateCard(token));
      await this.setCard(card);
      this.confirmationPending.set(false);
    } catch {
      this.errorMessage.set('Votre carte n’a pas pu être renouvelée. Réessayez.');
    } finally {
      this.rotating.set(false);
    }
  }

  private async setCard(card: CatalogMemberCard): Promise<void> {
    this.card.set(card);
    this.qrSvg.set(null);
    try {
      const qrCodeModule = await import('qrcode') as typeof import('qrcode') & {default?: typeof import('qrcode')};
      const toString = qrCodeModule.default?.toString ?? qrCodeModule.toString;
      const svg = await toString(card.qrPayload, {
        type: 'svg',
        errorCorrectionLevel: 'M',
        margin: 2,
      });
      // This SVG is generated by qrcode from the signed payload, not user-authored HTML.
      this.qrSvg.set(this.sanitizer.bypassSecurityTrustHtml(svg));
    } catch {
      this.errorMessage.set('Le QR code n’a pas pu être préparé sur cet appareil.');
    }
  }
}
