using '../main.bicep'

param environmentName = 'development'

// -----------------------------------------------------------------------
// Container Apps
// -----------------------------------------------------------------------
// Every image listens on 8080: the API through ASPNETCORE_URLS, the Website
// through the SSR server's PORT, the BackOffice through nginx.conf.

param containerAppApiContainerRuntime = {
  cpuCores: '0.5'
  memoryGi: '1.0Gi'
}
param containerAppApiScaling = {
  minReplicas: 1
  maxReplicas: 2
}
param containerAppApiIngress = {
  enabled: true
  targetPort: 8080
  external: true
  transportMethod: 'auto'
}
param containerAppApiHealthProbes = {
  readiness: {
    path: '/health'
    port: 8080
  }
  liveness: {
    path: '/health'
    port: 8080
  }
  startup: {
    path: '/health'
    port: 8080
  }
}

param containerAppWebsiteContainerRuntime = {
  cpuCores: '0.5'
  memoryGi: '1.0Gi'
}
param containerAppWebsiteScaling = {
  minReplicas: 1
  maxReplicas: 2
}
param containerAppWebsiteIngress = {
  enabled: true
  targetPort: 8080
  external: true
  transportMethod: 'auto'
}
param containerAppWebsiteHealthProbes = {
  readiness: {
    path: ''
    port: 0
  }
  liveness: {
    path: ''
    port: 0
  }
  startup: {
    path: ''
    port: 0
  }
}

// The root and WWW aliases point to the public Website. The BackOffice keeps
// its own hostname. The catalog hostname is intentionally left unbound until
// its Container App exists and the DNS/CNAME validation can be performed.
param websiteCustomDomain = 'volepapillondamour.fr'
param websiteWwwCustomDomain = 'www.volepapillondamour.fr'
param backOfficeCustomDomain = 'backoffice.volepapillondamour.fr'
// Names generated by Azure when the managed certificates were first issued.
param websiteCustomDomainCertificateName = 'volepapillondamour.fr-vpd-cae--260901180010'
param websiteWwwCustomDomainCertificateName = 'www.volepapillondamour.fr-vpd-cae--260901180118'
param backOfficeCustomDomainCertificateName = 'backoffice.volepapillondamou-vpd-cae--260902142245'
param catalogCustomDomain = ''
param catalogCustomDomainCertificateName = ''

param containerAppBackOfficeContainerRuntime = {
  cpuCores: '0.25'
  memoryGi: '0.5Gi'
}
param containerAppBackOfficeScaling = {
  minReplicas: 1
  maxReplicas: 2
}
param containerAppBackOfficeIngress = {
  enabled: true
  targetPort: 8080
  external: true
  transportMethod: 'auto'
}
param containerAppBackOfficeHealthProbes = {
  readiness: {
    path: ''
    port: 0
  }
  liveness: {
    path: ''
    port: 0
  }
  startup: {
    path: ''
    port: 0
  }
}

param containerAppScanContainerRuntime = {
  cpuCores: '0.25'
  memoryGi: '0.5Gi'
}
param containerAppScanScaling = {
  minReplicas: 1
  maxReplicas: 2
}
param containerAppScanIngress = {
  enabled: true
  targetPort: 8080
  external: true
  transportMethod: 'auto'
}
param containerAppScanHealthProbes = {
  readiness: {
    path: '/health'
    port: 8080
  }
  liveness: {
    path: '/health'
    port: 8080
  }
  startup: {
    path: '/health'
    port: 8080
  }
}

param containerAppCatalogContainerRuntime = {
  cpuCores: '0.5'
  memoryGi: '1.0Gi'
}
param containerAppCatalogScaling = {
  minReplicas: 1
  maxReplicas: 2
}
param containerAppCatalogIngress = {
  enabled: true
  targetPort: 8080
  external: true
  transportMethod: 'auto'
}
param containerAppCatalogHealthProbes = {
  readiness: {
    path: ''
    port: 0
  }
  liveness: {
    path: ''
    port: 0
  }
  startup: {
    path: ''
    port: 0
  }
}

param containerAppWorkerContainerRuntime = {
  cpuCores: '0.5'
  memoryGi: '1.0Gi'
}
// P1-1 measures whether a timer-triggered Function wakes correctly with no
// warm host. Keep one maximum replica while observing the production timer.
param containerAppWorkerScaling = {
  minReplicas: 0
  maxReplicas: 1
}

// -----------------------------------------------------------------------
// Platform
// -----------------------------------------------------------------------

param keyVaultSku = 'standard'
param keyVaultEnablePurgeProtection = false

// S1: fixed Standard tier, 20 DTUs and no automatic pause, as decided in DT-11.
// The subscription is not allowed to provision Azure SQL in West Europe
// (ProvisioningDisabled), so the database sits in France Central.
param sqlLocation = 'francecentral'

param sqlDatabaseName = 'vole-papillon-damour-db'
param sqlDatabaseSku = {
  name: 'S1'
  tier: 'Standard'
  capacity: 20
  maxSizeBytes: 268435456000
  autoPauseDelayMinutes: 0
}

param storageAccountSku = 'Standard_LRS'

// ACS Email is a global ARM resource; France is the data-residency geography.
// The sending domain is customer-managed and is verified through OVH DNS after
// the infrastructure deployment exposes its generated records.
param communicationEmailServiceName = 'vpd-acs-email-dev'
param communicationEmailDataLocation = 'France'
param communicationEmailSendingDomain = 'mail.volepapillondamour.fr'
param monitoringAlertEmail = 'volepapillondamour@sfr.fr'
param corsAllowedOrigins = [
  'https://volepapillondamour.fr'
  'https://www.volepapillondamour.fr'
  'https://backoffice.volepapillondamour.fr'
  'https://livres.volepapillondamour.fr'
  'https://vpd-scan-ca-dev.mangoground-a76d7dbc.westeurope.azurecontainerapps.io'
]

param entraAuthority = readEnvironmentVariable('ENTRA_AUTHORITY', 'https://volepapillondamour.ciamlogin.com/')
param entraTenantId = readEnvironmentVariable('ENTRA_TENANT_ID', 'b23c80b3-9776-4840-8255-fcbf3b3500fd')
// The API application ID is public configuration, recorded after L0-11 steps 1-2.
// Keep the environment-variable override for another deployment environment.
param entraApiClientId = readEnvironmentVariable('ENTRA_API_CLIENT_ID', 'ebc68507-2c07-4bab-9448-2d6d489c6112')
param entraGraphClientId = readEnvironmentVariable('ENTRA_GRAPH_CLIENT_ID', '')
param entraGraphClientSecret = readEnvironmentVariable('ENTRA_GRAPH_CLIENT_SECRET', '')

// Container names must match the BlobSettings section consumed by BlobService.
param blobContainerLotoImages = 'loto-images'
param blobContainerActualityImages = 'actuality-images'
param blobContainerEventImages = 'event-images'
param blobContainerProductImages = 'product-images'
param blobContainerBookCovers = 'book-covers'

param jwtIssuer = 'Vole_Papillon_Damour'
param jwtAudience = 'Vole_Papillon_Damour'
param jwtExpiryMinutes = 1000

// -----------------------------------------------------------------------
// Values injected by the pipeline
// -----------------------------------------------------------------------
// Secrets come from GitHub secrets and images from the current state of the
// Container Apps - never commit a value here.

param sqlAdministratorLogin = readEnvironmentVariable('SQL_ADMIN_LOGIN', 'vpdadmin')
param sqlAdministratorLoginPassword = readEnvironmentVariable('SQL_ADMIN_PASSWORD', '')
param jwtSecret = readEnvironmentVariable('JWT_SECRET', '')

param apiImage = readEnvironmentVariable('API_IMAGE', '')
param websiteImage = readEnvironmentVariable('WEBSITE_IMAGE', '')
param backOfficeImage = readEnvironmentVariable('BACKOFFICE_IMAGE', '')
param scanImage = readEnvironmentVariable('SCAN_IMAGE', '')
param catalogImage = readEnvironmentVariable('CATALOG_IMAGE', '')
param workerImage = readEnvironmentVariable('WORKER_IMAGE', '')
