<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Vole_Papillon_Damour.Contracts</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Vole_Papillon_Damour.Domain\Vole_Papillon_Damour.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="6.0.0-preview.4.21253.5" />
    </ItemGroup>
</Project>
