// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vole_Papillon_Damour.Infrastructure.Persistence;

#nullable disable

namespace Vole_Papillon_Damour.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20260903002636_AddAccountDeletionOutbox")]
    partial class AddAccountDeletionOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ActualityAggregate.Actuality", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPrincipalImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actualities", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BingoHasBeenWon")
                        .HasColumnType("bit");

                    b.Property<string>("BingoNumeros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentPartieIndex")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventsType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("HourCloseDoors")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HourOpenDoors")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImageMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents.Adresse#Adresse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CityCode")
                                .HasColumnType("int");

                            b1.Property<string>("Road")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("RoadNumber")
                                .HasColumnType("int");
                        });

                    b.HasKey("Id");

                    b.ToTable("AssoEvents", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("ProductSection")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisibleOnWebsite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "Vole_Papillon_Damour.Domain.UserAggregate.User.Name#Name", b1 =>
                        {
                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastError")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScanSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("ScanSessionId");

                    b.HasIndex("Status", "DueAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.Partie", "Parties", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PartieId");

                            b1.Property<Guid>("AssoEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AddedBingoNumber")
                                .HasColumnType("int");

                            b1.Property<int>("CurrentLineIndex")
                                .HasColumnType("int");

                            b1.Property<int>("Index")
                                .HasColumnType("int");

                            b1.Property<string>("LastNumeros")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LiveNumeros")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PartieType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PauseAfter")
                                .HasColumnType("bit");

                            b1.HasKey("Id", "AssoEventId");

                            b1.HasIndex("AssoEventId");

                            b1.ToTable("Parties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssoEventId");

                            b1.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.LinePartie", "LineParties", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("LinePartieId");

                                    b2.Property<Guid>("AssoEventId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Index")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("LinePartieId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("NumberLine")
                                        .HasColumnType("int");

                                    b2.Property<int>("NumberLotsToWin")
                                        .HasColumnType("int");

                                    b2.HasKey("Id", "AssoEventId");

                                    b2.HasIndex("LinePartieId", "AssoEventId");

                                    b2.ToTable("LinePartie", null, t =>
                                        {
                                            t.Property("LinePartieId")
                                                .HasColumnName("LinePartieId1");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("LinePartieId", "AssoEventId");

                                    b2.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.Lot", "Lots", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier")
                                                .HasColumnName("LotId");

                                            b3.Property<int>("Index")
                                                .HasColumnType("int");

                                            b3.Property<int?>("IsWon")
                                                .HasColumnType("int");

                                            b3.Property<Guid?>("LotId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid?>("LotsId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("UrlImage")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("LotsId", "LotId");

                                            b3.ToTable("Lots", null, t =>
                                                {
                                                    t.Property("LotId")
                                                        .HasColumnName("LotId1");
                                                });

                                            b3.WithOwner()
                                                .HasForeignKey("LotsId", "LotId");
                                        });

                                    b2.Navigation("Lots");
                                });

                            b1.Navigation("LineParties");
                        });

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.OrderAggregate.Entities.OrderedProduct", "Products", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OrderId");

                            b1.Property<Guid>("OrderedProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id", "OrderedProductId");

                            b1.HasIndex("OrderedProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("OrderedProducts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderedProductId");

                            b1.HasOne("Vole_Papillon_Damour.Domain.ProductAggregate.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Product");
                        });

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ProductAggregate.Product", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.ProductAggregate.ValueObjects.Promotion", "Promotions", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("PromotionId");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("DiscountedPrice")
                                .HasColumnType("float");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("Promotions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
