// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vole_Papillon_Damour.Infrastructure.Persistence;

#nullable disable

namespace Vole_Papillon_Damour.Infrastructure.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ActualityAggregate.Actuality", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Article")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FacebookLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InstagramLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlPrincipalImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Actualities", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BingoHasBeenWon")
                        .HasColumnType("bit");

                    b.Property<string>("BingoNumeros")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BookRevenue")
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("CurrentPartieIndex")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventsType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("HourCloseDoors")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("HourOpenDoors")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("IsCancelled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlImageMap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlRegistration")
                        .HasColumnType("nvarchar(max)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Adresse", "Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents.Adresse#Adresse", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("CityCode")
                                .HasColumnType("int");

                            b1.Property<string>("Road")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int?>("RoadNumber")
                                .HasColumnType("int");
                        });

                    b.HasKey("Id");

                    b.ToTable("AssoEvents", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssociationSettingsAggregate.AssociationSettings", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<int>("AlertCooldownDays")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(30);

                    b.Property<int>("AlertDelayMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(120);

                    b.Property<int>("DeadStockMinAgeDays")
                        .HasColumnType("int");

                    b.Property<int>("DeadStockMinQuantity")
                        .HasColumnType("int");

                    b.Property<int>("DemandSalesThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("DuplicateThreshold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<int>("SessionIdleTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(120);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("WatchlistMaxItems")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(100);

                    b.HasKey("Id");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("AssociationSettings", null, t =>
                        {
                            t.HasCheckConstraint("CK_AssociationSettings_SingletonId", "[Id] = 1");
                        });
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookAggregate.Book", b =>
                {
                    b.Property<string>("Id")
                        .IsUnicode(false)
                        .HasColumnType("char(13)")
                        .HasColumnName("Isbn13");

                    b.Property<string>("Authors")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<DateTime?>("CoverCheckedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("CoverSource")
                        .HasColumnType("tinyint");

                    b.Property<string>("CoverUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genre")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsHiddenFromCatalog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsRare")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Language")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAvailableAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ManuallyEditedFields")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MetadataFetchedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("MetadataSource")
                        .HasColumnType("tinyint");

                    b.Property<byte>("MetadataStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("PhysicalFormat")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PublicationYear")
                        .HasColumnType("int");

                    b.Property<string>("Publisher")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("QuantityAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RawPayload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RedirectedToIsbn13")
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<int>("RejectionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ResolveAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SalesCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .UseCollation("Latin1_General_100_CI_AI");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("WorkId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("RedirectedToIsbn13");

                    b.HasIndex("UpdatedAt");

                    b.HasIndex("WorkId");

                    b.HasIndex("MetadataStatus", "LastAttemptAt");

                    b.ToTable("Books", null, t =>
                        {
                            t.HasCheckConstraint("CK_Books_NoSelfRedirect", "[RedirectedToIsbn13] IS NULL OR [RedirectedToIsbn13] <> [Isbn13]");
                        });
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookAggregate.Entities.BookAnnouncement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssoEventsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientGestureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReleasedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ScanSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("AssoEventsId")
                        .HasFilter("[AssoEventsId] IS NULL");

                    b.HasIndex("Isbn13");

                    b.HasIndex("ScanSessionId");

                    b.HasIndex("AssoEventsId", "Status");

                    b.ToTable("BookAnnouncements", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookAnnouncements_Quantity_Positive", "[Quantity] > 0");
                        });
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookMovementAggregate.BookMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AssoEventsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientGestureId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ClockSuspect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ReversalOfMovementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ScanSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClientGestureId")
                        .IsUnique()
                        .HasFilter("[ClientGestureId] IS NOT NULL");

                    b.HasIndex("ReversalOfMovementId")
                        .IsUnique()
                        .HasFilter("[ReversalOfMovementId] IS NOT NULL");

                    b.HasIndex("ScanSessionId");

                    b.HasIndex("VolunteerId");

                    b.HasIndex("AssoEventsId", "Type");

                    b.HasIndex("Isbn13", "OccurredAt");

                    b.HasIndex("Isbn13", "Type", "OccurredAt");

                    b.ToTable("BookMovements", null, t =>
                        {
                            t.HasCheckConstraint("CK_BookMovements_Quantity_NonZero", "[Quantity] <> 0");
                        });
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.OrderAggregate.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ProductAggregate.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("ProductCategory")
                        .HasColumnType("int");

                    b.Property<int>("ProductSection")
                        .HasColumnType("int");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("VisibleOnWebsite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.HasKey("Id");

                    b.ToTable("Products", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ScanSessionAggregate.ScanSession", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte?>("CloseReason")
                        .HasColumnType("tinyint");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KeptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("LastScanAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LateArrivals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<byte>("Mode")
                        .HasColumnType("tinyint");

                    b.Property<int>("RejectedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("ScannedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<Guid?>("TargetAssoEventsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TargetAssoEventsId");

                    b.HasIndex("VolunteerId")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("ScanSessions", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Name", "Vole_Papillon_Damour.Domain.UserAggregate.User.Name#Name", b1 =>
                        {
                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");
                        });

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.EmailBounceEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderEventId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderEventId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("EmailBounceEvents", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.UserAlertHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Isbn13")
                        .IsRequired()
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<Guid?>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OutboxMessageId");

                    b.HasIndex("UserId", "Isbn13", "SentAt");

                    b.ToTable("UserAlertHistory", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.Watchlist", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<byte>("AlertStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.Property<int>("BounceCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Watchlists", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.WatchlistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Isbn13")
                        .IsUnicode(false)
                        .HasColumnType("char(13)");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WorkId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("Isbn13");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkId");

                    b.HasIndex("UserId", "Isbn13")
                        .IsUnique()
                        .HasFilter("[Isbn13] IS NOT NULL");

                    b.HasIndex("UserId", "WorkId")
                        .IsUnique()
                        .HasFilter("[WorkId] IS NOT NULL");

                    b.ToTable("WatchlistItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_WatchlistItems_ExactlyOneTarget", "(([Scope] = 0 AND [WorkId] IS NOT NULL AND [Isbn13] IS NULL) OR ([Scope] = 1 AND [WorkId] IS NULL AND [Isbn13] IS NOT NULL))");
                        });
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Infrastructure.Persistence.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Attempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("ClaimedUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Kind")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastError")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid?>("MemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ScanSessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)0);

                    b.HasKey("Id");

                    b.HasIndex("ScanSessionId");

                    b.HasIndex("Status", "DueAt");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.Partie", "Parties", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("PartieId");

                            b1.Property<Guid>("AssoEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int?>("AddedBingoNumber")
                                .HasColumnType("int");

                            b1.Property<int>("CurrentLineIndex")
                                .HasColumnType("int");

                            b1.Property<int>("Index")
                                .HasColumnType("int");

                            b1.Property<string>("LastNumeros")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("LiveNumeros")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Name")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PartieType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<bool>("PauseAfter")
                                .HasColumnType("bit");

                            b1.HasKey("Id", "AssoEventId");

                            b1.HasIndex("AssoEventId");

                            b1.ToTable("Parties", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("AssoEventId");

                            b1.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.LinePartie", "LineParties", b2 =>
                                {
                                    b2.Property<Guid>("Id")
                                        .HasColumnType("uniqueidentifier")
                                        .HasColumnName("LinePartieId");

                                    b2.Property<Guid>("AssoEventId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("Index")
                                        .HasColumnType("int");

                                    b2.Property<Guid?>("LinePartieId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<int>("NumberLine")
                                        .HasColumnType("int");

                                    b2.Property<int>("NumberLotsToWin")
                                        .HasColumnType("int");

                                    b2.HasKey("Id", "AssoEventId");

                                    b2.HasIndex("LinePartieId", "AssoEventId");

                                    b2.ToTable("LinePartie", null, t =>
                                        {
                                            t.Property("LinePartieId")
                                                .HasColumnName("LinePartieId1");
                                        });

                                    b2.WithOwner()
                                        .HasForeignKey("LinePartieId", "AssoEventId");

                                    b2.OwnsMany("Vole_Papillon_Damour.Domain.AssoEventsAggregate.Entities.Lot", "Lots", b3 =>
                                        {
                                            b3.Property<Guid>("Id")
                                                .HasColumnType("uniqueidentifier")
                                                .HasColumnName("LotId");

                                            b3.Property<int>("Index")
                                                .HasColumnType("int");

                                            b3.Property<int?>("IsWon")
                                                .HasColumnType("int");

                                            b3.Property<Guid?>("LotId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<Guid?>("LotsId")
                                                .HasColumnType("uniqueidentifier");

                                            b3.Property<string>("Name")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("UrlImage")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.HasKey("Id");

                                            b3.HasIndex("LotsId", "LotId");

                                            b3.ToTable("Lots", null, t =>
                                                {
                                                    t.Property("LotId")
                                                        .HasColumnName("LotId1");
                                                });

                                            b3.WithOwner()
                                                .HasForeignKey("LotsId", "LotId");
                                        });

                                    b2.Navigation("Lots");
                                });

                            b1.Navigation("LineParties");
                        });

                    b.Navigation("Parties");
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.AssociationSettingsAggregate.AssociationSettings", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookAggregate.Book", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.BookAggregate.Book", null)
                        .WithMany()
                        .HasForeignKey("RedirectedToIsbn13")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookAggregate.Entities.BookAnnouncement", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", null)
                        .WithMany()
                        .HasForeignKey("AssoEventsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vole_Papillon_Damour.Domain.BookAggregate.Book", null)
                        .WithMany()
                        .HasForeignKey("Isbn13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vole_Papillon_Damour.Domain.ScanSessionAggregate.ScanSession", null)
                        .WithMany()
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.BookMovementAggregate.BookMovement", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", null)
                        .WithMany()
                        .HasForeignKey("AssoEventsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vole_Papillon_Damour.Domain.BookAggregate.Book", null)
                        .WithMany()
                        .HasForeignKey("Isbn13")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vole_Papillon_Damour.Domain.BookMovementAggregate.BookMovement", null)
                        .WithMany()
                        .HasForeignKey("ReversalOfMovementId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vole_Papillon_Damour.Domain.ScanSessionAggregate.ScanSession", null)
                        .WithMany()
                        .HasForeignKey("ScanSessionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.OrderAggregate.Order", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.OrderAggregate.Entities.OrderedProduct", "Products", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier")
                                .HasColumnName("OrderId");

                            b1.Property<Guid>("OrderedProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("Id", "OrderedProductId");

                            b1.HasIndex("OrderedProductId");

                            b1.HasIndex("ProductId");

                            b1.ToTable("OrderedProducts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("OrderedProductId");

                            b1.HasOne("Vole_Papillon_Damour.Domain.ProductAggregate.Product", "Product")
                                .WithMany()
                                .HasForeignKey("ProductId")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.Navigation("Product");
                        });

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ProductAggregate.Product", b =>
                {
                    b.OwnsMany("Vole_Papillon_Damour.Domain.ProductAggregate.ValueObjects.Promotion", "Promotions", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasColumnName("PromotionId");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<double>("DiscountedPrice")
                                .HasColumnType("float");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("ProductId", "Id");

                            b1.ToTable("Promotions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("Promotions");
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.ScanSessionAggregate.ScanSession", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.AssoEventsAggregate.AssoEvents", null)
                        .WithMany()
                        .HasForeignKey("TargetAssoEventsId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.EmailBounceEvent", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.UserAlertHistory", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Infrastructure.Persistence.Outbox.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.Watchlist", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.UserAggregate.User", null)
                        .WithOne()
                        .HasForeignKey("Vole_Papillon_Damour.Domain.WatchlistAggregate.Watchlist", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vole_Papillon_Damour.Domain.WatchlistAggregate.WatchlistItem", b =>
                {
                    b.HasOne("Vole_Papillon_Damour.Domain.WatchlistAggregate.Watchlist", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
