// =======================================================================
// Azure Monitor workbook module
// -----------------------------------------------------------------------
// Deploys the shared "VPD - Performance et santé" workbook. Every query runs
// against the common Log Analytics workspace, so one page follows a request
// from the browser through the API and the worker.
// The JSON is generated by workbooks/generate-performance-workbook.mjs.
// =======================================================================

@description('Azure region of the workbook')
param location string

@description('Display name of the workbook')
param displayName string

@description('Resource ID of the Log Analytics workspace queried by the workbook')
param workspaceId string

@description('Resource tags')
param tags object = {}

resource workbook 'Microsoft.Insights/workbooks@2023-06-01' = {
  // A workbook name must be a GUID; keep it stable so redeployments update in place.
  name: guid(resourceGroup().id, 'vpd-performance-workbook')
  location: location
  tags: tags
  kind: 'shared'
  properties: {
    displayName: displayName
    category: 'workbook'
    sourceId: workspaceId
    version: 'Notebook/1.0'
    serializedData: replace(loadTextContent('workbooks/vpd-performance.workbook.json'), '__WORKSPACE_ID__', workspaceId)
  }
}

@description('Resource ID of the workbook')
output resourceId string = workbook.id
