<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
      <UserSecretsId>3af4547e-7898-4c08-bcb0-8f452e799be0</UserSecretsId>
      <RootNamespace>Vole_Papillon_Damour.Api</RootNamespace>
  </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.5.0" />
        <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" Version="1.8.0" />
        <PackageReference Include="Mapster" Version="10.0.7" />
        <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.7" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Vole_Papillon_Damour.Contracts\Vole_Papillon_Damour.Contracts.csproj" />
        <ProjectReference Include="..\Vole_Papillon_Damour.Application\Vole_Papillon_Damour.Application.csproj" />
        <ProjectReference Include="..\Vole_Papillon_Damour.Infrastructure\Vole_Papillon_Damour.Infrastructure.csproj" />
    </ItemGroup>
</Project>
